name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    name: "build (gradle-versions=${{ matrix.gradle-versions}}; publish=${{ matrix.publish }})"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            gradle-versions:
                - 5.3,5.6
                - 6.0,6.6
            publish:
                - false
            include:
                - gradle-versions: 6.7
                  publish: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Pull docker images
        run: 'bash -c "docker pull alfresco/alfresco-content-repository-community:6.0.7-ga& docker pull tomcat:7-jre8& docker pull hello-world& docker pull alpine:edge&"'
      - name: Check
        run: ./gradlew check -PintegrationTestGradleVersions=${{ matrix.gradle-versions }}
      - name: Upload analysis to sonarcloud
        if: ${{ matrix.publish }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_alfresco-docker-gradle-plugin -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.publish }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGINS_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGINS_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
